export {default as China} from "./china.svg?react";
export {default as France} from "./france.svg?react";
export {default as UK} from "./uk.svg?react";
export {default as Germany} from "./germany.svg?react";
export {default as Israel} from "./israel.svg?react";
export {default as Japan} from "./japan.svg?react";
export {default as Russia} from "./russia.svg?react";
export {default as UAE} from "./uae.svg?react";
export {default as Spain} from "./spain.svg?react";
